---
- name: 'Install epel-release'
  yum:
    name: epel-release
    state: present

- name: 'Install packages on ovpn-server'
  yum:
    name:
      - openvpn
      - easy-rsa
      - iperf3
      - tcpdump
      - policycoreutils-python
    state: present
  when: (ansible_hostname == 'ovpn-server')

- name: 'Install packages on ovpn-client'
  yum:
    name:
      - openvpn
      - iperf3
    state: present
  when: (ansible_hostname == 'ovpn-client')

- name: 'Copy config for loopback'
  template:
    src: ifcfg-lo.2.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-lo.2
  notify:
    - restart network
  
- name: 'Enable forwarding'
  copy:
    src: ip_forwarding.conf
    dest: /etc/sysctl.d/
  notify:
    - restart network

# - name: 'Remove client.conf on client'
#   file:
#     path: /etc/openvpn/client.conf
#     state: absent
#   when: (ansible_hostname == 'ovpn-client')
#   notify:
#     - stop openvpn client

- name: 'Copy secret key'
  copy:
    src: static.key
    dest: /etc/openvpn/

- name: 'Copy server.conf to ovpn-server'
  template:
    src: server-server.conf.j2
    dest: /etc/openvpn/server.conf
  when: (ansible_hostname == 'ovpn-server')
  notify:
    - restart openvpn server

- name: 'Copy server.conf to ovpn-client'
  template:
    src: server-client.conf.j2
    dest: /etc/openvpn/server.conf
  when: (ansible_hostname == 'ovpn-client')
  notify:
    - restart openvpn server
